modName=HorizonRadio
modId=horizonradio
modGroup=com.horizonradio
modVersion=1.4.1
minecraftVersion=1.7.10
forgeVersion=10.13.4.1614
channel=stable
mappingsVersion=12
developmentEnvironmentUserName=HorizonRadioDev
usesMixins=false
enableModernJavaSyntax=jabel
enableGenericInjection=true

useModGroupForPublishing=true
autoUpdateBuildScript=false
includeWellKnownRepositories=true
generateGradleTokenClass=com.horizonradio.Tags
gradleTokenVersion=VERSION
org.gradle.configuration-cache=true
org.gradle.parallel=true
